# Generated by Django 2.1.5 on 2019-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bcomment',
            field=models.IntegerField(db_column='comment', default=0),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(auto_now_add=True, db_column='pub_date'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(db_column='read', default=0),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(db_column='title', max_length=20),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcomment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
